// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget.sql

package db

import (
	"context"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (user_id, category_id, amount)
VALUES ($1, $2, $3)
RETURNING id, user_id, category_id, amount, created_at
`

type CreateBudgetParams struct {
	UserID     int64
	CategoryID int64
	Amount     string
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget, arg.UserID, arg.CategoryID, arg.Amount)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}

const getBudget = `-- name: GetBudget :one
SELECT id, user_id, category_id, amount, created_at FROM budgets
WHERE id = $1 AND user_id = $2
`

type GetBudgetParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listBudgetsByUser = `-- name: ListBudgetsByUser :many
SELECT id, user_id, category_id, amount, created_at FROM budgets
WHERE user_id = $1
`

func (q *Queries) ListBudgetsByUser(ctx context.Context, userID int64) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, listBudgetsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET amount = $1
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, category_id, amount, created_at
`

type UpdateBudgetParams struct {
	Amount string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, updateBudget, arg.Amount, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
