// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (user_id, category_id, amount, note, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, category_id, amount, note, date, created_at
`

type CreateExpenseParams struct {
	UserID     int64
	CategoryID int64
	Amount     string
	Note       sql.NullString
	Date       time.Time
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND user_id = $2
`

type DeleteExpenseParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpense, arg.ID, arg.UserID)
	return err
}

const getExpense = `-- name: GetExpense :one
SELECT id, user_id, category_id, amount, note, date, created_at FROM expenses
WHERE id = $1 AND user_id = $2
`

type GetExpenseParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpense, arg.ID, arg.UserID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}

const listExpensesByUser = `-- name: ListExpensesByUser :many
SELECT id, user_id, category_id, amount, note, date, created_at FROM expenses
WHERE user_id = $1
ORDER BY date DESC
`

func (q *Queries) ListExpensesByUser(ctx context.Context, userID int64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Note,
			&i.Date,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET category_id = $1, amount = $2, note = $3, date = $4
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, category_id, amount, note, date, created_at
`

type UpdateExpenseParams struct {
	CategoryID int64
	Amount     string
	Note       sql.NullString
	Date       time.Time
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpense,
		arg.CategoryID,
		arg.Amount,
		arg.Note,
		arg.Date,
		arg.ID,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Note,
		&i.Date,
		&i.CreatedAt,
	)
	return i, err
}
