// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Budget struct {
	ID         int64
	UserID     int64
	CategoryID int64
	Amount     string
	CreatedAt  time.Time
}

type Category struct {
	ID        int64
	UserID    int64
	Name      string
	CreatedAt time.Time
}

type Expense struct {
	ID         int64
	UserID     int64
	CategoryID int64
	Amount     string
	Note       sql.NullString
	Date       time.Time
	CreatedAt  time.Time
}

type User struct {
	ID        int64
	Email     string
	Password  string
	CreatedAt time.Time
}
